select graph_curso.nome as nome, graph_curso.id as curso_id
from graph_curso
         left join graph_cursocampus on graph_curso.id = graph_cursocampus.curso_id
         left join graph_campus on graph_cursocampus.campus_id = graph_campus.id
where graph_campus.nome = 'Anápolis';


insert into graph_campus (id, nome)
values (DEFAULT, 'Águas Lindas'),
       (DEFAULT, 'Anápolis'),
       (DEFAULT, 'Aparecida de Goiânia'),
       (DEFAULT, 'Cidade de Goiás'),
       (DEFAULT, 'Goiânia'),
       (DEFAULT, 'Goiânia Oeste'),
       (DEFAULT, 'Inhumas'),
       (DEFAULT, 'Itumbiara'),
       (DEFAULT, 'Jataí'),
       (DEFAULT, 'Luziânia'),
       (DEFAULT, 'Senador Canedo'),
       (DEFAULT, 'Uruaçu'),
       (DEFAULT, 'Valparaíso');

insert into graph_curso (id, nome)
values (DEFAULT, 'Licenciatura em Ciências Biológicas'),
       (DEFAULT, 'Bacharelado em Ciência da Computação'),
       (DEFAULT, 'Bacharelado em Engenharia Civil da Mobilidade'),
       (DEFAULT, 'Licenciatura em Ciências Sociais'),
       (DEFAULT, 'Mestrado Profissional em Educação Profissional e Tecnológica'),
       (DEFAULT, 'Licenciatura em Dança'),
       (DEFAULT, 'Licenciatura em Pedagogia Bilíngue'),
       (DEFAULT, 'Bacharelado em Agronomia'),
       (DEFAULT, 'Bacharelado em Cinema e Audiovisual'),
       (DEFAULT, 'Licenciatura em Artes Visuais'),
       (DEFAULT, 'Especialização em Educação para Cidadania'),
       (DEFAULT, 'Bacharelado em Engenharia Ambiental e Sanitária'),
       (DEFAULT, 'Bacharelado em Engenharia Cartográfica e de Agrimensura'),
       (DEFAULT, 'Bacharelado em Engenharia de Transportes'),
       (DEFAULT, 'Bacharelado em Engenharia Elétrica'),
       (DEFAULT, 'Bacharelado em Engenharia Mecânica'),
       (DEFAULT, 'Bacharelado em Química'),
       (DEFAULT, 'Bacharelado em Turismo'),
       (DEFAULT, 'Licenciatura em História'),
       (DEFAULT, 'Licenciatura em Letras - Língua Portuguesa'),
       (DEFAULT, 'Licenciatura em Matemática'),
       (DEFAULT, 'Licenciatura em Música'),
       (DEFAULT, 'Especialização em Gestão dos Serviços de Hospitalidade'),
       (DEFAULT, 'Especialização em Matemática'),
       (DEFAULT, 'Especialização em Políticas e Gestão da Educação Profissional e Tecnológica'),
       (DEFAULT, 'Especialização em Telecomunicações: Prédios Inteligentes'),
       (DEFAULT, 'Mestrado Profissional em Tecnologia de Processos Sustentáveis'),
       (DEFAULT, 'Licenciatura em Pedagogia'),
       (DEFAULT, 'Bacharelado em Ciência e Tecnologia de Alimentos'),
       (DEFAULT, 'Bacharelado em Sistemas de Informação'),
       (DEFAULT, 'Licenciatura em Química'),
       (DEFAULT, 'Especialização em Docência na Educação Básica e Profissional'),
       (DEFAULT, 'Bacharelado em Engenharia de Controle e Automação'),
       (DEFAULT, 'Especialização em Ensino de Ciências e Matemática'),
       (DEFAULT, 'Especialização em Fontes Renováveis de Energia'),
       (DEFAULT, 'Bacharelado em Engenharia Civil'),
       (DEFAULT, 'Licenciatura em Física'),
       (DEFAULT, 'Mestrado Profissional em Educação para Ciências e Matemática'),
       (DEFAULT, 'Especialização em Docência em Educação e Tecnologia'),
       (DEFAULT, 'Bacharelado em Engenharia de Produção');

insert into graph_cursocampus (campus_id, curso_id)
values (1, 1), (2, 2), (2, 3),
       (2, 4),
       (2, 31),
       (2, 5),
       (3, 36),
       (3, 6),
       (3, 7),
       (4, 8),
       (4, 9),
       (4, 10),
       (14, 36),
       (14, 1),
       (14, 4),
       (14, 11),
       (5, 12),
       (5, 13),
       (5, 16),
       (5, 33),
       (5, 14),
       (5, 15),
       (5, 16),
       (5, 17),
       (5, 30),
       (5, 18),
       (5, 37),
       (5, 19),
       (5, 20),
       (5, 21),
       (5, 22),
       (5, 23),
       (5, 24),
       (5, 25),
       (5, 26),
       (5, 27),
       (6, 28),
       (7, 29),
       (7, 30),
       (7, 31),
       (7, 32),
       (8, 33),
       (8, 15),
       (8, 31),
       (8, 34),
       (8, 35),
       (9, 36),
       (9, 15),
       (9, 37),
       (9, 38),
       (10, 30),
       (10, 31),
       (10, 39),
       (11, 40),
       (12, 36),
       (12, 31),
       (13, 15),
       (13, 21);

insert into graph_eixo (id, eixo)
values (DEFAULT, 'Desenvolvimento Institucional'),
       (DEFAULT, 'Políticas de Gestão'),
       (DEFAULT, 'Infraestrutura');

insert into graph_dimensao (dimensao, eixo_id)
values ('Missão Institucional e PDI', 1),
       ('Responsabilidade Social', 1),
       ('Políticas de Pessoal', 2),
       ('Organização e Gestão da Instituição', 2),
       ('Estrutura Física', 3);