version: "3.5"
services:
  nginx:
    image: nginx:latest
    container_name: cpa_nginx
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - /static:/static
    depends_on:
      - web
    environment:
      VIRTUAL_HOST: cpa.bcc.anapolis.ifg.edu.br
      VIRTUAL_PORT: 8000
  web:
    build: .
    container_name: cpa_app
    restart: always
    command: sh -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && gunicorn cpadash.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db2
    volumes:
      - ./src:/src
      - /static:/static
    expose:
      - "8000"
    environment:
      DATABASE_PASS: cpadash2019
      DATABASE_HOST: db2
      DATABASE_PORT: 5432
      DATABASE_NAME: cpadash
  db2:
    image: postgres:alpine
    container_name: cpa_db
    restart: always
    volumes:
      - postgres_cpa:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cpadash
      POSTGRES_PASSWORD: cpadash2019
      PGDATA: /var/lib/postgresql/data/pgdata
      LANG: pt_BR.utf8
    ports:
      - "5433:5432"
volumes:
  postgres_cpa:
    external: true

networks:
  default:
    external:
      name: nginx-proxy
      