# Generated by Django 2.2 on 2021-02-24 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atuacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Atuacao',
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Campus',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Curso',
            },
        ),
        migrations.CreateModel(
            name='CursoCampus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.IntegerField(null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.Campus')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.Curso')),
            ],
            options={
                'verbose_name_plural': 'CursoCampus',
            },
        ),
        migrations.CreateModel(
            name='Dimensao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensao', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Dimensao',
            },
        ),
        migrations.CreateModel(
            name='Eixo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eixo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Eixo',
            },
        ),
        migrations.CreateModel(
            name='Lotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Lotacao',
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('tipo', models.IntegerField(default=1)),
                ('dimensao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='graph.Dimensao')),
            ],
            options={
                'verbose_name_plural': 'Pergunta',
            },
        ),
        migrations.CreateModel(
            name='RespostaObjetiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=24)),
                ('value', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Segmento',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atuacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='graph.Atuacao')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='graph.CursoCampus')),
                ('lotacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='graph.Lotacao')),
                ('segmento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='graph.Segmento')),
            ],
            options={
                'verbose_name_plural': 'Pessoa',
            },
        ),
        migrations.CreateModel(
            name='PerguntaSegmento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(choices=[(2019, 2019), (2020, 2020), (2021, 2021)], default=2021)),
                ('atuacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='graph.Atuacao')),
                ('lotacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='graph.Lotacao')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.Pergunta')),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.Segmento')),
            ],
            options={
                'verbose_name_plural': 'PerguntaSegmento',
            },
        ),
        migrations.CreateModel(
            name='ParticipacaoPergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_subjetiva', models.TextField(null=True)),
                ('ano', models.IntegerField(default=2021, null=True)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.Pergunta')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.Pessoa')),
                ('res_objetiva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='graph.RespostaObjetiva')),
            ],
            options={
                'verbose_name_plural': 'ParticipacaoPergunta',
            },
        ),
        migrations.AddField(
            model_name='dimensao',
            name='eixo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='graph.Eixo'),
        ),
    ]
