# Generated by Django 2.2 on 2021-03-20 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(choices=[(2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=2021)),
                ('grafico_publico', models.BooleanField(default=False)),
                ('questionario_publico', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Questionários',
            },
        ),
        migrations.RemoveField(
            model_name='perguntasegmento',
            name='ano',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='ano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graph.Questionario'),
        ),
    ]
