# Generated by Django 2.2.6 on 2019-10-03 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='campus',
        ),
        migrations.CreateModel(
            name='CursoCampus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.Campus')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.Curso')),
            ],
            options={
                'verbose_name_plural': 'CursoCampus',
            },
        ),
    ]
