# Generated by Django 2.2 on 2021-03-20 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_auto_20210319_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pergunta',
            old_name='ano',
            new_name='questionario',
        ),
    ]
