# Generated by Django 2.2 on 2021-03-20 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_auto_20210319_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionario',
            old_name='questionario_publico',
            new_name='perguntas_publico',
        ),
    ]
