# Generated by Django 2.2.6 on 2019-10-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0004_auto_20191007_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
