# Generated by Django 2.2.6 on 2019-10-07 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0005_auto_20191007_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursocampus',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.Campus'),
        ),
        migrations.AlterField(
            model_name='cursocampus',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.Curso'),
        ),
        migrations.AlterField(
            model_name='pessoacurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.Curso'),
        ),
        migrations.AlterField(
            model_name='pessoacurso',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.Pessoa'),
        ),
    ]
