# Generated by Django 2.2 on 2021-03-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0005_auto_20210319_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='ano',
            field=models.IntegerField(default=2021),
        ),
    ]
