# Generated by Django 2.2.6 on 2019-10-07 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0006_auto_20191007_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atuacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Atuacao',
            },
        ),
        migrations.AddField(
            model_name='pessoa',
            name='atuacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='graph.Atuacao'),
        ),
    ]
