# Generated by Django 2.2.6 on 2019-10-07 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0007_auto_20191007_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tema',
            old_name='titulo',
            new_name='dimensao',
        ),
        migrations.AddField(
            model_name='tema',
            name='eixo',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
