# Generated by Django 2.2.6 on 2019-10-07 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0008_auto_20191007_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimensao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Dimensao',
            },
        ),
        migrations.CreateModel(
            name='Eixo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eixo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Eixo',
            },
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='tema',
        ),
        migrations.DeleteModel(
            name='Tema',
        ),
        migrations.AddField(
            model_name='dimensao',
            name='eixo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='graph.Eixo'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='dimensao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='graph.Dimensao'),
        ),
    ]
