# Generated by Django 2.2.6 on 2019-10-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0009_auto_20191007_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='quant',
        ),
        migrations.AddField(
            model_name='cursocampus',
            name='quant',
            field=models.IntegerField(null=True),
        ),
    ]
