# Generated by Django 2.2.6 on 2019-10-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0010_auto_20191007_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participacaopergunta',
            name='resposta',
        ),
        migrations.AddField(
            model_name='participacaopergunta',
            name='res_objetiva',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='participacaopergunta',
            name='res_subjetiva',
            field=models.TextField(null=True),
        ),
    ]
