# Generated by Django 2.2.6 on 2019-10-07 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0011_auto_20191007_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaObjetiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='participacaopergunta',
            name='res_objetiva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='graph.RespostaObjetiva'),
        ),
    ]
