# Generated by Django 2.2.6 on 2019-10-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0012_auto_20191007_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='tipo',
            field=models.IntegerField(default=1),
        ),
    ]
