# Generated by Django 2.2.6 on 2019-10-07 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0014_perguntasegmento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntasegmento',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.Pergunta'),
        ),
        migrations.AlterField(
            model_name='perguntasegmento',
            name='segmento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.Segmento'),
        ),
    ]
