# Generated by Django 2.2.6 on 2019-10-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0015_auto_20191007_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmento',
            name='nome',
            field=models.CharField(max_length=64),
        ),
    ]
