# Generated by Django 2.2.6 on 2019-10-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0017_auto_20191007_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostaobjetiva',
            name='value',
            field=models.IntegerField(default=1),
        ),
    ]
