# Generated by Django 2.2.6 on 2019-10-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0018_respostaobjetiva_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostaobjetiva',
            name='titulo',
            field=models.CharField(max_length=24),
        ),
    ]
