# Generated by Django 2.2.6 on 2019-10-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0019_auto_20191007_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='nome',
        ),
    ]
