# Generated by Django 2.2.6 on 2019-10-14 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0021_auto_20191008_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('segmento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graph.Segmento')),
            ],
            options={
                'verbose_name_plural': 'Lotacao',
            },
        ),
    ]
