# Generated by Django 2.2.6 on 2019-10-14 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0025_auto_20191014_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='atuacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='graph.Atuacao'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='lotacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='graph.Lotacao'),
        ),
    ]
