# Generated by Django 2.2.6 on 2019-10-15 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0026_auto_20191014_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotacao',
            options={'verbose_name_plural': 'Lotacoes'},
        ),
    ]
