# Generated by Django 2.2.6 on 2019-10-22 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0027_auto_20191015_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='graph.CursoCampus'),
        ),
        migrations.DeleteModel(
            name='PessoaCurso',
        ),
    ]
