# Generated by Django 2.2 on 2020-03-21 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0028_auto_20191022_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacaopergunta',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
