# Generated by Django 2.2 on 2020-03-21 21:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0029_participacaopergunta_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacaopergunta',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 21, 3, 53, 181583, tzinfo=utc)),
        ),
    ]
