# Generated by Django 2.2 on 2020-10-16 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0032_auto_20200321_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacaopergunta',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 10, 16, 13, 47, 12, 479301, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='perguntasegmento',
            name='ano',
            field=models.IntegerField(choices=[(2019, 2019), (2020, 2020)], default=2020),
        ),
    ]
