# Generated by Django 2.2 on 2020-10-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0033_auto_20201016_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participacaopergunta',
            name='time',
        ),
        migrations.AddField(
            model_name='participacaopergunta',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
