# Generated by Django 2.2 on 2021-01-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0035_auto_20201016_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntasegmento',
            name='ano',
            field=models.IntegerField(choices=[(2019, 2019), (2020, 2020), (2021, 2021)], default=2021),
        ),
    ]
