# Generated by Django 2.2 on 2021-01-14 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0036_auto_20210114_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotacao',
            options={'verbose_name_plural': 'Lotacao'},
        ),
    ]
