# Generated by Django 2.2 on 2021-01-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0037_auto_20210114_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacaopergunta',
            name='ano',
            field=models.IntegerField(default=2021, null=True),
        ),
    ]
