# Generated by Django 2.2 on 2021-01-15 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0038_auto_20210114_2202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grafico',
        ),
    ]
