name: Deploy to IFG Anápolis BCC

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Deploy CPA Dash
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVICES_HOST }}
        username: ${{ secrets.SERVICES_USER }}
        key: ${{ secrets.SERVICES_SSH_PRIVATE_KEY }}
        script: |
          cd cpa/cpadashdocker && git checkout master && git pull
          docker-compose down
          docker-compose up --build -d
