name: Deploy to IFG Anápolis BCC

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Deploy CPA Dash
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /home/anapolis/cpadash/cpadashdocker/ && git checkout master && git pull
          docker-compose down
          docker-compose up --build -d
